# Generated by Django 2.1.3 on 2018-11-14 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clss', '0002_auto_20181114_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('clss_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clss.Clss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('clss.clss',),
        ),
    ]
