# Generated by Django 2.0.9 on 2018-11-15 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clss', '0003_auto_20181115_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='participate',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='studentname',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
